config/routes.rb
Rails.application.routes.draw do
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'


  get 'contact', to: 'pages#contact'
  get 'about-me', to: 'pages#about'
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @portfolio_items = Portfolio.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    def index
        @portfolio_items = Portfolio.all
    end

    def show
        @portfolio_item = Portfolio.find(params[:id])
    end

    def new
        @portfolio_item = Portfolio.new
    end

    def create
        @portfolio_item = Portfolio.new(params.require(:portfolio).permit(:title, :subtile, :body))

        respond_to do |format|
            if @portfolio_item.save 
                format.html { redirect_to portfolios_path, notice: "Your portfolio item is now live" }
            else
                format.html {render :new}
            end
        end
    end

    def edit
        @portfolio_item = Portfolio.find(params[:id])
    end

    def update
        @portfolio_item = Portfolio.find(params[:id])
        respond_to do |format|
            if @portfolio_item.update(params.require(:portfolio).permit(:title, :subtile, :body)) 
                format.html { redirect_to portfolios_path, notice: "Your portfolio item has been updated" }
            else
                format.html {render :edit}
            end
        end
    end

    def destroy
        @portfolio_item = Portfolio.find(params[:id])
        @portfolio_item.destroy
        respond_to do |format|
            format.html {redirect_to portfolios_path, notice: 'Portfolio was removed.'}
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Home Page</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<p><%= @portfolio_items.inspect %></p>

app/views/portfolios/edit.html.erb
<h1>Edit this portfolio item</h1>

<%= form_with model: @portfolio_item do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %> <br>

    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %><br>
    
    <%= form.label :body %>
    <%= form.text_area :body, size: "60x10" %><br>
    
    <%= form.submit %>
<% end %>

app/views/portfolios/index.html.erb
<h1>Portfolio</h1>

<%= link_to "Create New portfolio item", new_portfolio_path %>

<% @portfolio_items.each do |portfolio_item|%>
    <h2><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></h2>
    <p><%= portfolio_item.subtitle %></p>
    <p><%= portfolio_item.body %></p>
    <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil?  %>
    <br>
    <%= link_to "Edit", edit_portfolio_path(portfolio_item.id) %>
    <%= link_to "Delete Portfolio item", portfolio_path(portfolio_item), method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>

app/views/portfolios/new.html.erb
<h1>New Portfolio</h1>

<%= form_with model: @portfolio_item do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %> <br>

    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %><br>
    
    <%= form.label :body %>
    <%= form.text_area :body, size: "60x10" %><br>
    
    <%= form.submit %>
<% end %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image unless @portfolio_item.thumb_image.nil?  %>
<h1><%= @portfolio_item.title %></h1>
<em><%= @portfolio_item.subtitle %></em>
<p><%= @portfolio_item.body %></p>
<br>
<%= link_to "Edit", edit_portfolio_path(@portfolio_item.id) %>
<br>
<br>
<br>
<%= params.inspect %>